### ISSUE TITLE
Broken link http://www.mroth.net/lunit/ 

### ISSUE THREAD

**Issue by italomaia** [sam-github/lunit#2]
Hello folks! http://www.mroth.net/lunit/  pointed out here http://lua-users.org/wiki/UnitTesting as home of lua unit testing, is a broken link.

**Comment by sam-github** [comment]
@italomaia I don't use lunit anymore, and don't have an interest in maintaining it, though its easy enough for me to accept a PR if you think its worth your time.

/to @moteus or @dcurrie  It looks like you two have active forks.

Would you like me to add a note in the top of the README or description of sam-github/lunit pointing to either of your forks?
